### ISSUE TITLE
Feature request: simulate fixed CDR3 length

### ISSUE THREAD

**Issue by scharch** [psathyrella/partis#249]
Low priority, since I can always filter, but seems like it would be easy to implement and would save computing time for questions where it's relevant.

**Comment by psathyrella** [comment]
Good idea.

Quick fix: copy your parameter dir, pull up all-probs.csv (full joint counts), and remove all the lines with wrong cdr3. Or, since these are the full rearrangement events, and simulation is basically just choosing lines: just delete/modify it down to the lines (exact rearrangement events) you want.

**Comment by psathyrella** [comment]
I added the functional columns to default simulation files (as described ^), I'll get to the actual cdr3 filtering somewhat, um, later.
