### ISSUE TITLE
recommendation for non-stranded reads?

### ISSUE THREAD

**Issue by alexpan82** [psathyrella/partis#306]
Hello!

I am working with VDJ data generated from a non-stranded RNA-seq library. 

Do you have any recommendations on running partis efficiently on such a data set besides running it again on the revcomp?

On that note, why does partis only accept plus-strand reads? 

Thanks,
Alex

**Comment by psathyrella** [comment]
Partis doesn't do any kind of preprocessing (i.e. paired read joining, primer masking, error correction, etc), and getting everything plus-stranded makes more sense to us as part of preprocessing, since it's a trivial alignment step that doesn't require the improved accuracy of partis's smith waterman or hmm methods. That said I did recently add bin/split-loci.py as a simple script to split apart h/k/l, and it'd be easy to make a similar helper script for converting to all plus-stranded.

**Comment by psathyrella** [comment]
I did it!

https://github.com/psathyrella/partis/blob/dev/bin/split-loci.py#L27

**Comment by psathyrella** [comment]
For the benefit of future searchers -- partis now also accepts the --reverse-negative-strands option (although it's just running split-loci.py)

https://github.com/psathyrella/partis/blob/dev/docs/quick-start.md
