### ISSUE TITLE
disable germline inference

### ISSUE THREAD

**Issue by krishnaroskin** [psathyrella/partis#312]
Duncan and co,

The command line arguments make reference to being able to disable germline inference. Is that possible?

I have a bunch of sequences from different people that I want annotate. I was hoping to do this in on batch to save time. It also seems like the support values don't have much meaning when run on a single sequence.

Thanks for a great tool,
-krish

**Comment by psathyrella** [comment]
Glad you're enjoying it! Yes, you can turn off germline inference with `--leave-default-germline`, which... wow, somehow it doesn't even have a help message, let alone a link in the docs. I'll make sure to add that.

**Comment by krishnaroskin** [comment]
Thanks for super fast responce!

Then maybe I was confused by the V support numbers. I was thinking that if you used `--leave-default-germline` (and we have been) and you run 10 sequences, the support numbers should be the same as if you ran each sequence by itself. Maybe that's an incorrect reading of that number?

**Comment by psathyrella** [comment]
No, you're right, that's what the number is trying to measure. The problem is just that it's quite heuristic really, which I know I've written about somewhere but it must be buried in an issue or email since I don't see it in the docs/output-formats.md (i'll fix that). So in principle it's easy -- just add up the probabilities for the paths for one gene vs the others. But there's a lot of heuristic optimizations that go into which genes get run in the hmm (e.g. the smith waterman only tells the hmm about the best N genes via --n-max-per-region), and if memory serves (it's been a long time since i looked at this) the hmm "factorization" (bottom of p21 [here](https://arxiv.org/pdf/1503.04224.pdf)), while being absolutely necessary from a speed standpoint, it speeds things up by a couple orders of magnitude, also means that you can't just read off a lot of the probabilities of things that you might expect to be able to.

So I have done a fair bit of validation of the per-gene support numbers, and they do generally have a nice monotonic relationship to the probability that a gene is actually correct (although not perfectly linear, darn it, where are those plots?), but there are caveats. I think it's correct to say, though, that these caveats mostly apply to genes that do or don't appear in the support, though. Like numbers should be comparable if all the genes are the same? Or are you seeing very different numbers with the same genes?

**Comment by psathyrella** [comment]
couple other thoughts

  - while things should generally work fine on only a few sequences, everything in partis is kind of designed around the idea of caching parameters on a large sample, and then doing inference. So when you only have one or a few sequences, you'll just generally have to be more careful about what's going on to make sure results, especially detailed ones like the support numbers, are sensible. For instance maybe running cache-parameters as a separate step just to make sure they're getting cached properly for each sequence.
  - EDIT oh wait, duh, i just tried to do this and realized that assuming you are caching parameters on each individual sequence that the per gene support  won't be meaningful at all -- I forgot that it only writes an hmm model file for the best sw match for each sequence, and if there's only one sequence then there's only one for each of v, d, j. Humorously, this is exactly the kind of thing I was alluding to in the previous paragraph, but without remembering this particular detail. In the past we've talked about setting up a sort of "global prior" set of cached parameters that would on average be a good choice for running individual sequences from, say, all humans. But it hasn't been a high priority, and it's also hard to imagine knowing all the demographic characteristics that we'd need to know about, although there really are at this point probably enough public samples to think about doing this. 
   - If you really want visibility into what's going on with the hmm, you can set --debug 2 (maybe also with --sw-debug 0), this'll print absolutely everything the hmm does.

**Comment by psathyrella** [comment]
i could see an argument that "disabling germline inference" should really mean "write hmms for ~all possible genes, rather than just those that are best matches to a sequence", which might not be a very hard thing to implement. I forget whether it's set up that way for some specific reason, or just because i was only caring about inferring on large samples.

**Comment by krishnaroskin** [comment]
One of my students found a case where the top V call changed based on if the sequence analyze together or by itself. I haven't had time to track that down and provide the examples but I'm working on it! Sorry for the delay.

**Comment by psathyrella** [comment]
Yeah getting different results depending on other sequences run with it is an inherent (though perhaps inadvertent) result of the overall architecture. In many (most?) cases, this is what we want it to do -- for instance if additional sequences give better information to infer a different germline set, or better mutation or insertion parameters, then we want different results. But I for sure understand that it's not ideal/not how you'd necessarily expect it to behave, and should probably be explained better in the docs. The basic thing is that it infers parameters before actually inferring the results (whether the cache-parameters step is run automatically or by hand), and those parameters will be different if the input sequences are different.
