### ISSUE TITLE
Issue with annotate

### ISSUE THREAD

**Issue by ayeletperes** [psathyrella/partis#327]
Hey, I've been running the align command with a custom reference set using the docker image, sometimes it works and sometimes it crashes. The only thing that changes between the runs is the query file. I attached below the code I'm running and the error message.

`docker run -v /home/:/work quay.io/matsengrp/partis bin/partis annotate --infname /work/query.fasta --outfname /work/query.yaml --n-procs 20 --initial-germline-dir /work/data/germline/human --airr-output --extra-annotation-columns regional_bounds
`
```
/partis/bin/partis:19: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(scipy.__version__) < StrictVersion('0.17.0'):
  note: writing both partis .yaml to /work/query.yaml and airr .tsv to /work/query.tsv
  note: set tree inference outdir to /work/query
  note: --parameter-dir not set, so using default: _output/_query
  parameter dir does not exist, so caching a new set of parameters before running action 'annotate': _output/query
  warning multiple names in /work/data/germline/human/igh/ighd.fasta for the following sequences:
    IGHD4-11*01 IGHD4-4*01                               TGACTACAGTAACTAC
    IGHD5-18*01 IGHD5-5*01                               GTGGATACAGCTATGGTTAC
  it is highly recommended to remove the duplicates to avoid ambiguity
caching parameters
  vsearch: 28896 / 30000 v annotations (1104 failed) with 83 v genes in 2.4 sec
    keeping 12 / 198 v genes
smith-waterman  (new-allele fitting)
  vsearch: 28841 / 30000 v annotations (1159 failed) with 12 v genes in 4.9 sec
    running 20 procs for 30000 seqs
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/colored_traceback/colored_traceback.py", line 27, in colorize_traceback
    tb_colored = pygments.highlight(tb_text, lexer, self.formatter)
  File "/opt/conda/lib/python3.9/site-packages/colored_traceback/colored_traceback.py", line 32, in formatter
    colors = _get_term_color_support()
  File "/opt/conda/lib/python3.9/site-packages/colored_traceback/colored_traceback.py", line 66, in _get_term_color_support
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database

Original exception was:
Traceback (most recent call last):
  File "/partis/bin/partis", line 1633, in <module>
    args.func(args)
  File "/partis/bin/partis", line 334, in run_partitiondriver
    parter.run(actions)
  File "/partis/python/partitiondriver.py", line 133, in run
    self.action_fcns[tmpaction]()
  File "/partis/python/partitiondriver.py", line 328, in cache_parameters
    self.run_waterer(dbg_str='new-allele fitting')
  File "/partis/python/partitiondriver.py", line 235, in run_waterer
    waterer.run(cachefname if write_cachefile else None)
  File "/partis/python/waterer.py", line 115, in run
    self.read_output(base_outfname, len(mismatches))
  File "/partis/python/waterer.py", line 506, in read_output
    qinfo = self.read_query(sam.references, readlist)
  File "/partis/python/waterer.py", line 569, in read_query
    indelfo = indelutils.get_indelfo_from_cigar(read.cigarstring, qinfo['seq'], qrbounds, self.glfo['seqs'][region][gene], glbounds, {region : gene}, uid=qinfo['name'])  # note that qinfo['seq'] differs from self.input_info[qinfo['name']]['seqs'][0] if we've already reversed an indel in this sequence   
  File "/partis/python/indelutils.py", line 312, in get_indelfo_from_cigar
    check_cigar_len(cigars, qrseq, glseq, uid=uid, debug=debug)
  File "/partis/python/indelutils.py", line 272, in check_cigar_len
    raise IndelfoReconstructionError()  # ok i still don't like this but it happens
python.indelutils.IndelfoReconstructionError
```

**Comment by psathyrella** [comment]
hmm, sorry about that. That's very weird, the smith waterman aligner seems to be passing an inconsistent cigar string, which I've never seen before. I'm not sure I'll be able to fix it without more detail, is there any way you could pass the data so I could run on it, or failing that, run with --debug 2 and pass the output of that?

The (incidental) setupterm error I'm pretty sure has to do with the environment from which you're running the Docker command, but I've never encountered it, so my first guess is it might be a macos thing? If so it would be great to get some insight into how to fix it since I don't have immediate access to a mac to try things out.

**Comment by ayeletperes** [comment]
I'm acutely running on a Debian system. I've fixed the first problem with sending an environment variable (in the code below) to the docker. 

`(docker run **-e NCURSES_TERMINFO=/usr/share/terminfo -e TERM=xterm** --rm -v /.../partis_test/:/work quay.io/matsengrp/partis bin/partis annotate --infname /work/test_set.fasta --outfname /work/test_set.yaml --initial-germline-dir /work/human --airr-output --extra-annotation-columns regional_bounds --debug 2) > /.../partis_test/log.txt`

I've attached a sample file and the log report from the debug. [partis_test.zip](https://github.com/psathyrella/partis/files/14627395/partis_test.zip)

**Comment by psathyrella** [comment]
Huh, that's weird it happens on debian, I'm not sure why TERM & co wouldn't be set. I've never run into it, so if you have any suggestions for what I could do in the docker file to fix it that'd be appreciated. 

It turns out there's a few sequences in your sample that kick up bad cigar strs from Smith-Waterman. Which is weird it's never happened before, but the sample does have a ton of indels and is quite mutated with lots of ambiguous bases, which all increase the chances of weird matches. But the sample isn't very big, so, I don't know. Anyway [this commit](https://github.com/psathyrella/partis/commit/d0ea1142393ea469f3555c9ea362fb4d30f513dc) fixes it, the auto build should be finished and propagated to quay within a few hours. The seqs in question now just print warnings:

![warnings](https://github.com/psathyrella/partis/assets/2960243/d92f48c0-930a-42ad-9dd5-60bff7a59277)

I also notice in the debug log you sent that a lot of the indels are identical:
![indels](https://github.com/psathyrella/partis/assets/2960243/1a3ae13c-f7b2-4f8e-a259-e374ad9b3cc0)


 i.e. look like there might be a germline gene with an indel relative to the initial germline set, so I ran with [`--allele-cluster`](https://github.com/psathyrella/partis/blob/dev/docs/subcommands.md#germline-sets) to turn on the clustering-style germline inference, which indeed called a gene with this indel:

![germline-indel](https://github.com/psathyrella/partis/assets/2960243/65d4ac6a-068c-4d68-a7a4-d4ebea380834)

Without knowing the sample provenance, I don't know if this is real or an artifact of sequencing, but it looks like your germline set is pretty much the same as the ogrdb one that partis has, just with a bunch of V genes renamed and with the last few bases trimmed off (see attached output of `./bin/cf-germlines.py data/germlines/human partis_test/human|less -RS`)

[cf-gl.log](https://github.com/psathyrella/partis/files/14628162/cf-gl.log)

**Comment by ayeletperes** [comment]
Thanks! The sequences are indeed artificial, and the sample contains just two alleles of V that I heavily mutated and inserted indels. The reference is based on the one from ogrdb, but the names we're changed for testing.  So the results doesn't surprise me. But I guess I inserted too many to cause the error.

**Comment by psathyrella** [comment]
Ah, cool, that makes sense. Definitely not too many! It's gotta be able to handle any sequence you can throw at it. It's probably most likely that something about the python 3 change from a month or so ago kicked up this error.
